### PR TITLE
#170947388 User role setting

### PR DESCRIPTION
**Pull request by AbdoulNuru**
#### What does this PR do?
- implement user role settings functionality
#### Description of Task to be completed?
- create user role settings component
- add client-side validations
- write tests

#### How should this be manually tested?
- clone the repo, then checkout to this branch ``ft-user-role-settings-170947388``
- run `npm i` to install all project dependencies
- run `npm run dev` to start the development server
- login as a super administrator and assign a role to someone to test, use credentials below to login
```
email: abdoulniyigena@gmail.com
password: password
```

#### What are the relevant pivotal tracker stories?
[#170947388](https://www.pivotaltracker.com/story/show/170947388)
#### Screenshots (if appropriate)
Screen Shot 2020-05-06 at 17 31 07

On errors
Screen Shot 2020-05-06 at 17 31 17

### CODE REVIEW

**Review by Moise1 — COMMENTED** [review]
Good job @AbdoulNuru , but please raise your coverage back up again,

**Comment by blaise82** [comment]
please consider the design 
set role

**Review by hakoemmy — APPROVED** [review]

**Comment by AbdoulNuru** [comment]
> please consider the design
> set role

@blaise82 check the screenshots again.

**Comment by AbdoulNuru** [comment]
> > please consider the design
> > set role
> 
> @blaise82 check the screenshots again.

@blaise82 There are things I won't really add, cos they don't add value to the feature am working on right now.

**Review by Moise1 — APPROVED** [review]

**Review by blaise82 — APPROVED** [review]

**Review by blaise82 — APPROVED** [review]

**Pull request merged**
