### PR TITLE
#170947383 Users update profile

### PR DESCRIPTION
**Pull request by hakoemmy**
#### What does this PR do?
- This PR sets up user profile
#### Description of Task to be completed?
- Allow users to view/update their profile
- Allow user to upload image to the cloudinary
- Configure internationalization
#### How should this be manually tested?
- Clone the repo
- checkout this branch
- Run ```npm i```
- Run ``` npm run test```
- Run ``` npm run dev```
- And check out this URL: ```http://localhost:8080/profile```
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170947383](https://www.pivotaltracker.com/story/show/170947383)
### Profile page with avatar 

Screen Shot 2020-05-07 at 19 19 15

### Dashboard update profile

Screen Shot 2020-05-07 at 17 44 44

#### Questions:
N/A

### CODE REVIEW

**Comment by blaise82** [comment]
1. someone must not go to update the profile page if he or she isn't logged in
2. please read again the story for this feature 
 https://www.pivotaltracker.com/story/show/170947383 so that you may understand what's required of you more 

eg: Users should be able to view and edit their profiles (this means when I am on the profile page I must be able to view my data and see if I can decide to update it)

3. Please give space to the form. you compressed it a lot and there is space.

**Design Example**
sign up -1


- don't use highlisted dropdowns.

**Comment by AbdoulNuru** [comment]
@hakoemmy the coverage is dropping you can look at that as well

**Comment by hakoemmy** [comment]
> 1. someone must not go to update the profile page if he or she isn't logged in
> 2. please read again the story for this feature
>    https://www.pivotaltracker.com/story/show/170947383 so that you may understand what's required of you more
> 
> eg: Users should be able to view and edit their profiles (this means when I am on the profile page I must be able to view my data and see if I can decide to update it)
> 
> 1. Please give space to the form. you compressed it a lot and there is space.
> 
> **Design Example**
> sign up -1
> 
> * don't use highlisted dropdowns.

> @blaise82 I implemented your feedback for showing data and profile picture

**Comment by blaise82** [comment]
please consider the design 

update profile


I logged in as a normal user and I didn't see a link which takes to my profile so I had to just go in the URL and add it. if you follow the design those issues won't be there.

**Review by AbdoulNuru — APPROVED** [review]

**Comment by hakoemmy** [comment]
> please consider the design
> 
> update profile
> 
> I logged in as a normal user and I didn't see a link which takes to my profile so I had to just go in the URL and add it. if you follow the design those issues won't be there.

> You're right and I incorporated your feedback

**Review by Moise1 — APPROVED** [review]

**Pull request merged**
