### PR TITLE
#170947408 Users like/Unlike accommodation facility

### PR DESCRIPTION
**Pull request by hakoemmy**
#### What does this PR do?
- Like/Unlike an accommodation facility on barefoot nomad
#### Description of Task to be completed?
- Add liking functionality
- Add unliking functionality
#### How should this be manually tested?
- Clone the repo
- checkout this branch ```ft-like-unlike-accom-170947408```
- Run ``` npm install``` to install all dependencies in the project
- Run ```npm run test``` to fire up unit tests
- Run ```npm run dev``` to start the server
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170947408](https://www.pivotaltracker.com/story/show/170947408)
### Before
Screen Shot 2020-06-02 at 19 41 55

### After
Screen Shot 2020-06-02 at 19 42 09

#### Questions:
N/A

### CODE REVIEW

**Comment by blaise82** [comment]
working as expected

**Comment by hakoemmy** [comment]
> working as expected

@blaise82 It's my pleasure to hear that from you. Thanks for the heads up

**Review by AbdoulNuru — APPROVED** [review]

**Review by blaise82 — APPROVED** [review]

**Review by Moise1 — APPROVED** [review]
Good job.

**Comment by hakoemmy** [comment]
> Good job.

@Moise1 It's my pleasure to hear that from you. Thanks a lot for heads up

**Pull request merged**
